import { Inter, Poppins } from "next/font/google";
import "../../globals.css";
import Header from "../../_components/header";

// Inter font not working

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className} font-poppins`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
