import { Inter, Poppins } from "next/font/google";
import "@/app/globals.css";
import Header from "@/app/_components/checkoutHeader";
import store from "@/app/redux/store";
import { Providers } from "@/app/redux/provider";
import Footer from "@/app/_components/checkoutFooter";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.className} font-poppins bg-neutral-60`}
      >
        <Header />

        <Providers store={store}>{children}</Providers>

        <Footer />
      </body>
    </html>
  );
}
